const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Date,
		C3.Plugins.CBhash,
		C3.Plugins.LocalStorage,
		C3.Plugins.Timeline,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Behaviors.scrollto,
		C3.Plugins.HTMLElement,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.gamepad.Acts.VibrateDualRumble,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.gamepad.Exps.ButtonIndex,
		C3.Plugins.gamepad.Cnds.SupportsGamepad,
		C3.Plugins.gamepad.Cnds.OnGamepadConnected,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.gamepad.Exps.GamepadCount,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.gamepad.Cnds.OnGamepadDisconnected,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Timeline.Acts.StopTimelineByTags,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Timeline.Acts.PlayTimelineByName,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Timeline.Cnds.IsAnyPlaying,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.ScriptsInEvents.Sheetleaderboards_Event25_Act1,
		C3.ScriptsInEvents.Sheetleaderboards_Event26_Act1,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.regexreplace,
		C3.ScriptsInEvents.Sheetleaderboards_Event32_Act4,
		C3.Plugins.HTMLElement.Acts.InsertContent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.HTMLElement.Acts.SetContentClass,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Browser.Cnds.IsOnline,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Exps.int,
		C3.ScriptsInEvents.Sheetleaderboards_Event48_Act4,
		C3.Plugins.CBhash.Acts.MD5_hash,
		C3.Plugins.CBhash.Exps.get_lastResult,
		C3.Plugins.AJAX.Acts.Post,
		C3.ScriptsInEvents.Sheetleaderboards_Event62_Act4,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.gamepad.Exps.GamepadIndex,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Timeline.Acts.SetTimelineTimeByTags,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.gamepad.Cnds.OnAnyButtonUp,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Acts.StopAnim
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Timer: 0},
	{SpriteGBIntroText: 0},
	{SpritePlazIcon: 0},
	{SpritePlazFace: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{Browser: 0},
	{AJAX: 0},
	{Date: 0},
	{CBHash: 0},
	{LocalStorage: 0},
	{TimelineController: 0},
	{PlatformInfo: 0},
	{thisInstanceName: 0},
	{Flash: 0},
	{SpriteFontCGPixel4x5: 0},
	{SpriteFontGameboy: 0},
	{SpriteFontCGPixel3x5Custom: 0},
	{SpriteFontSignage: 0},
	{SpriteFontLargeNumbers: 0},
	{Fade: 0},
	{TileFlash: 0},
	{"9PatchBoxBorder": 0},
	{thisButtonIndex: 0},
	{thisButtonName: 0},
	{thisIsDisabled: 0},
	{thisIsAToggleButton: 0},
	{thisIsToggledOn: 0},
	{SpriteButtonSmall: 0},
	{thisButtonType: 0},
	{thisCharacter: 0},
	{thisRow: 0},
	{thisColumn: 0},
	{thisIsSelected: 0},
	{SpriteInvisibleButton: 0},
	{thisIsSceneAnimPlaying: 0},
	{SpriteAnimManager: 0},
	{SpritePlayerArrow: 0},
	{ScrollTo: 0},
	{TileCamera: 0},
	{SpriteGamepad: 0},
	{thisSelectedIndex: 0},
	{thisActiveTab: 0},
	{thisSelectedName: 0},
	{SpriteCursor: 0},
	{thisTimer: 0},
	{SpriteTimer: 0},
	{"9PatchWhite": 0},
	{TileLoaderMeter: 0},
	{SpriteLoaderMeterBorder: 0},
	{Sprite: 0},
	{thisCurrentCharIndex: 0},
	{thisCurrentCharName: 0},
	{thisCharacterRoster: 0},
	{thisCharacterRosterName: 0},
	{thisHasControl: 0},
	{SpriteSelectManager: 0},
	{SpriteMenuLogoSmall: 0},
	{SpriteMenuButtons: 0},
	{SpriteGameIntro004: 0},
	{SpriteMenuLogo: 0},
	{SpriteMenuLogo2: 0},
	{SpriteLeaderboardButtons: 0},
	{HTMLElement: 0},
	{ArrayHighScores: 0},
	{thisSelectIndex: 0},
	{SpriteOptionsOnOff: 0},
	{SpriteOptionsRoundTime: 0},
	{SpriteOptionsKeyConfig: 0},
	{SpriteNameInputBG: 0},
	{SpriteButtonGameMode: 0},
	{thisLabelIndex: 0},
	{SpriteLabelGameMode: 0},
	{SpriteHeroTie: 0},
	{SpriteFist: 0},
	{SpriteOptionsKeyConfigTabs: 0},
	{thisIsAwaitingKeyInput: 0},
	{SpriteOptionsKeyConfigPlayer: 0},
	{thisTimerInputTime: 0},
	{thisTempKey: 0},
	{thisTempPlayer: 0},
	{thisTempAction: 0},
	{thisTempDevice: 0},
	{SpriteOptionsKeyConfigReset: 0},
	{ArrayCustomControls: 0},
	{ArrayDefaultControls: 0},
	{SpriteGameIntro002: 0},
	{thisPlayerNumber: 0},
	{thisIsPressed: 0},
	{thisIsExtended: 0},
	{SpriteScreenControls: 0},
	{RecoveryTimer: 0},
	{SpriteLifebarKO: 0},
	{ParticlesSweatCollision: 0},
	{SpriteLifebarPortraits: 0},
	{thisRoundTimer: 0},
	{thisRoundPoints: 0},
	{thisIsRoundActive: 0},
	{thisIsRoundPaused: 0},
	{thisRoundWinner: 0},
	{thisPauseMenu: 0},
	{RoundTimer: 0},
	{AITimer: 0},
	{FreezeTimer: 0},
	{SpriteGameMaster: 0},
	{SpriteLifebarBorder: 0},
	{TileLifeMeter: 0},
	{"9PatchUIBackground": 0},
	{thisPlayerState: 0},
	{thisIsHuman: 0},
	{thisControl: 0},
	{thisPlayerLife: 0},
	{thisPlayerLifePercent: 0},
	{thisPlayerLifeRecoverable: 0},
	{thisPlayerLifeRecoverablePercent: 0},
	{thisGuardMeter: 0},
	{thisGotHitCount: 0},
	{thisZOrder: 0},
	{thisStatLifeFull: 0},
	{thisStatGuardMeterFull: 0},
	{thisGuardMeterPercent: 0},
	{thisStatDamageJab: 0},
	{thisStatDamageHook: 0},
	{thisStatBlockDamper: 0},
	{thisAIBlock: 0},
	{SpriteFighter: 0},
	{TileRing: 0},
	{SpriteCrowd: 0},
	{thisIsAlreadyCollided: 0},
	{thisDamage: 0},
	{thisAttackType: 0},
	{thisPlayer: 0},
	{SpriteHitBox: 0},
	{TileGuardMeter: 0},
	{SpriteCoach: 0},
	{ArrayCharacterData: 0},
	{TileLifeRecoverableMeter: 0},
	{SpriteSignageFight: 0},
	{SpriteSignageKO: 0},
	{SpriteHitSparkMedium: 0},
	{SpriteHitSparkStrong: 0},
	{SpriteFXGuardBreak: 0},
	{SpriteHitSparkWeak: 0},
	{SpriteFXCameraFlash: 0},
	{ArrayInputFlags: 0},
	{SpriteHitSparkBlocked: 0},
	{SpriteHitSparkParry: 0},
	{SpriteStaminaMeterBorder: 0},
	{TileStaminaMeter: 0},
	{SpriteVersus: 0},
	{SpriteVersusPortrait: 0},
	{ArrayQuotes: 0},
	{SpriteMenuRoundsButton: 0},
	{SpriteGameIntro001: 0},
	{SpriteGameOver: 0},
	{SpriteGameIntro003: 0},
	{SpriteCreditsContainer: 0},
	{SpriteCreditsMask: 0},
	{FamilyButtons: 0},
	{FamilyButtonLabels: 0},
	{FamilyFXNoLoop: 0},
	{pCurrentSelectedIndex: 0},
	{pIsIncrement: 0},
	{pSelectedIndex: 0},
	{hashValue: 0},
	{gOptionsIsMusicOn: 0},
	{gOptionsIsSoundFXOn: 0},
	{gOptionsIsScoreSubmissionOn: 0},
	{gOptionsRoundTime: 0},
	{gMAX_CHARS_USERNAME: 0},
	{gNameP1: 0},
	{gNameP2: 0},
	{gCharP1: 0},
	{gCharP2: 0},
	{gCurrentPlayerIndex: 0},
	{gGameMode: 0},
	{gIsP1Human: 0},
	{gIsP2Human: 0},
	{gScoreP1: 0},
	{gScoreP2: 0},
	{gWinStreakP1: 0},
	{gHighestRoundScore: 0},
	{gWinStreakP2: 0},
	{gWinTarget: 0},
	{gNameInputPlayerIndex: 0},
	{gRoundWinner: 0},
	{gMAX_LOCAL_SCORES: 0},
	{SCRIPTS_FOLDER: 0},
	{gPOINT_MULTIPLIER_JAB: 0},
	{gPOINT_MULTIPLIER_HOOK: 0},
	{gPOINT_GUARD_BREAK: 0},
	{gPOINT_KO: 0},
	{gBLOCK_DAMPER: 0},
	{S: 0},
	{S2: 0},
	{gGAMEPAD_AXIS_TOLERANCE: 0},
	{gPrimaryControl: 0},
	{nameArray: 0},
	{isEmpty: 0},
	{tempScoreString: 0},
	{tempScoreName: 0},
	{tempTimeStampString: 0},
	{pCandidateName: 0},
	{pCandidateScore: 0},
	{pCandidateTimeStamp: 0},
	{onlineScoresString: 0},
	{onlineScoresCount: 0},
	{candidateName: 0},
	{candidateScore: 0},
	{candidateTimeStamp: 0},
	{tempWinsScoreString: 0},
	{onlineWinScoresCount: 0},
	{candidateWins: 0},
	{pMessage: 0},
	{pTabToSelect: 0},
	{pUID: 0},
	{pOnOffToggle: 0},
	{pItem: 0},
	{tempButtonName: 0},
	{pIsIncrementJump: 0},
	{pJumpNum: 0},
	{pTab: 0},
	{pAction: 0},
	{pPlayer: 0},
	{pDevice: 0},
	{pPlayerNumber: 0},
	{pTypedKey: 0},
	{pPressedButton: 0},
	{pStoredKey: 0},
	{pInputDevice: 0},
	{pKey: 0},
	{tempLowestLife: 0},
	{pSubtrahend: 0},
	{pAddend: 0},
	{pIsConstrainedByRecover: 0},
	{pAmount: 0},
	{pNumberOfTimes: 0},
	{pSelectedName: 0},
	{pChar1: 0},
	{pChar2: 0},
	{pIsHuman: 0},
	{pGameMode: 0},
	{flashDuration: 0},
	{pMakeVisible: 0},
	{pMove: 0},
	{pIsPressed: 0},
	{tempCellData: 0},
	{statsColumn: 0},
	{statsRow: 0},
	{pCharacter: 0},
	{pP1Char: 0},
	{pP2Char: 0},
	{pPoints: 0},
	{pPlayerName: 0},
	{pScore: 0},
	{pTimeStamp: 0},
	{tempQuote: 0},
	{pWinner: 0},
	{pIsWinner: 0},
	{moveSeed: 0},
	{pInfo: 0},
	{pCharacterRosterID: 0},
	{pPlaySound: 0}
];

self.InstanceType = {
	SpriteGBIntroText: class extends self.ISpriteInstance {},
	SpritePlazIcon: class extends self.ISpriteInstance {},
	SpritePlazFace: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	CBHash: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	SpriteFontCGPixel4x5: class extends self.ISpriteFontInstance {},
	SpriteFontGameboy: class extends self.ISpriteFontInstance {},
	SpriteFontCGPixel3x5Custom: class extends self.ISpriteFontInstance {},
	SpriteFontSignage: class extends self.ISpriteFontInstance {},
	SpriteFontLargeNumbers: class extends self.ISpriteFontInstance {},
	TileFlash: class extends self.ITiledBackgroundInstance {},
	_9PatchBoxBorder: class extends self.IWorldInstance {},
	SpriteButtonSmall: class extends self.ISpriteInstance {},
	SpriteInvisibleButton: class extends self.ISpriteInstance {},
	SpriteAnimManager: class extends self.ISpriteInstance {},
	SpritePlayerArrow: class extends self.ISpriteInstance {},
	TileCamera: class extends self.ITiledBackgroundInstance {},
	SpriteGamepad: class extends self.ISpriteInstance {},
	SpriteCursor: class extends self.ISpriteInstance {},
	SpriteTimer: class extends self.ISpriteInstance {},
	_9PatchWhite: class extends self.IWorldInstance {},
	TileLoaderMeter: class extends self.ITiledBackgroundInstance {},
	SpriteLoaderMeterBorder: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	SpriteSelectManager: class extends self.ISpriteInstance {},
	SpriteMenuLogoSmall: class extends self.ISpriteInstance {},
	SpriteMenuButtons: class extends self.ISpriteInstance {},
	SpriteGameIntro004: class extends self.ISpriteInstance {},
	SpriteMenuLogo: class extends self.ISpriteInstance {},
	SpriteMenuLogo2: class extends self.ISpriteInstance {},
	SpriteLeaderboardButtons: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	ArrayHighScores: class extends self.IArrayInstance {},
	SpriteOptionsOnOff: class extends self.ISpriteInstance {},
	SpriteOptionsRoundTime: class extends self.ISpriteInstance {},
	SpriteOptionsKeyConfig: class extends self.ISpriteInstance {},
	SpriteNameInputBG: class extends self.ISpriteInstance {},
	SpriteButtonGameMode: class extends self.ISpriteInstance {},
	SpriteLabelGameMode: class extends self.ISpriteInstance {},
	SpriteHeroTie: class extends self.ISpriteInstance {},
	SpriteFist: class extends self.ISpriteInstance {},
	SpriteOptionsKeyConfigTabs: class extends self.ISpriteInstance {},
	SpriteOptionsKeyConfigPlayer: class extends self.ISpriteInstance {},
	SpriteOptionsKeyConfigReset: class extends self.ISpriteInstance {},
	ArrayCustomControls: class extends self.IArrayInstance {},
	ArrayDefaultControls: class extends self.IArrayInstance {},
	SpriteGameIntro002: class extends self.ISpriteInstance {},
	SpriteScreenControls: class extends self.ISpriteInstance {},
	SpriteLifebarKO: class extends self.ISpriteInstance {},
	ParticlesSweatCollision: class extends self.IParticlesInstance {},
	SpriteLifebarPortraits: class extends self.ISpriteInstance {},
	SpriteGameMaster: class extends self.ISpriteInstance {},
	SpriteLifebarBorder: class extends self.ISpriteInstance {},
	TileLifeMeter: class extends self.ITiledBackgroundInstance {},
	_9PatchUIBackground: class extends self.IWorldInstance {},
	SpriteFighter: class extends self.ISpriteInstance {},
	TileRing: class extends self.ITiledBackgroundInstance {},
	SpriteCrowd: class extends self.ISpriteInstance {},
	SpriteHitBox: class extends self.ISpriteInstance {},
	TileGuardMeter: class extends self.ITiledBackgroundInstance {},
	SpriteCoach: class extends self.ISpriteInstance {},
	ArrayCharacterData: class extends self.IArrayInstance {},
	TileLifeRecoverableMeter: class extends self.ITiledBackgroundInstance {},
	SpriteSignageFight: class extends self.ISpriteInstance {},
	SpriteSignageKO: class extends self.ISpriteInstance {},
	SpriteHitSparkMedium: class extends self.ISpriteInstance {},
	SpriteHitSparkStrong: class extends self.ISpriteInstance {},
	SpriteFXGuardBreak: class extends self.ISpriteInstance {},
	SpriteHitSparkWeak: class extends self.ISpriteInstance {},
	SpriteFXCameraFlash: class extends self.ISpriteInstance {},
	ArrayInputFlags: class extends self.IArrayInstance {},
	SpriteHitSparkBlocked: class extends self.ISpriteInstance {},
	SpriteHitSparkParry: class extends self.ISpriteInstance {},
	SpriteStaminaMeterBorder: class extends self.ISpriteInstance {},
	TileStaminaMeter: class extends self.ITiledBackgroundInstance {},
	SpriteVersus: class extends self.ISpriteInstance {},
	SpriteVersusPortrait: class extends self.ISpriteInstance {},
	ArrayQuotes: class extends self.IArrayInstance {},
	SpriteMenuRoundsButton: class extends self.ISpriteInstance {},
	SpriteGameIntro001: class extends self.ISpriteInstance {},
	SpriteGameOver: class extends self.ISpriteInstance {},
	SpriteGameIntro003: class extends self.ISpriteInstance {},
	SpriteCreditsContainer: class extends self.ISpriteInstance {},
	SpriteCreditsMask: class extends self.ISpriteInstance {},
	FamilyButtons: class extends self.ISpriteInstance {},
	FamilyButtonLabels: class extends self.ISpriteInstance {},
	FamilyFXNoLoop: class extends self.ISpriteInstance {}
}